# URL Scraper Tool Configuration
scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 30

rate_limit:
  max_requests: 50
  time_window_seconds: 60 